{
 "title": "Charon + Lodestar Logs",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Top Warnings and Errors",
   "type": "timeseries",
   "description": "Top 10 count of errors and warning per minute grouped by message. ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "topk(10,sum(count_over_time({service=\"charon\"} | logfmt | level=~`(WARN|ERRO)` | label_format level=\"{{trunc 1 .level | upper}}\"[1m])) by (level,msg,topic))",
     "legendFormat": "{{level}} [{{topic}}] {{msg}}"
    }
   ]
  },
  {
   "title": "Duty Failed Reasons",
   "type": "logs",
   "description": "Reasons why duties failed prefixed by slot and duty type",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "{service=\"charon\"} | logfmt | msg=`Duty failed` | line_format `{{.duty}}\t{{.reason}}`"
    }
   ]
  },
  {
   "title": "Charon Logs",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "{service=\"charon\"} |= ``"
    }
   ]
  },
  {
   "title": "Lodestar Errors",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{service_name=\"lodestar\"} |= ``"
    }
   ]
  }
 ]
}