{
 "title": "Charon Overview v3",
 "tags": [
  "cluster-labels",
  "charon"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster_name", "label": "Cluster Name", "query": { "query": "label_values(cluster_name)" } },
   {
    "name": "cluster_hash",
    "label": "Cluster Hash",
    "query": {
     "query": "label_values(app_peer_name{cluster_name=\"$cluster_name\"}, cluster_hash)"
    }
   },
   {
    "name": "cluster_peer",
    "label": "Cluster Peer",
    "query": {
     "query": "label_values(app_peer_name{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\"}, cluster_peer)"
    }
   },
   {
    "name": "job",
    "label": "--",
    "query": {
     "query": "label_values(app_peer_name{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"},job)"
    }
   },
   {
    "name": "peer",
    "label": "P2P Peer",
    "query": {
     "query": "label_values(app_peerinfo_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\", cluster_peer=\"$cluster_peer\"}, peer)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "duty",
    "label": "Duty",
    "query": "attester,prepare_aggregator,aggregator,sync_message,prepare_sync_contribution,sync_contribution,proposer,randao,exit,builder_proposer,builder_registration,info_sync"
   },
   {
    "name": "cluster_network",
    "label": "Cluster Network",
    "query": {
     "query": "label_values(app_peer_name{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"},cluster_network)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Health Status",
   "type": "stat",
   "description": "Status returned from the `/readyz` health status endpoint. Unhealthy reasons include beacon node problems, charon p2p problems, or validator client problems.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}"
    }
   ]
  },
  {
   "title": "Cluster Duty Success(%) ",
   "type": "gauge",
   "description": "Successful cluster duty percentage by type over the whole time range",
   "gridPos": { "h": 7, "w": 14, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(\n    sum(increase(core_tracker_success_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__range])) by (duty)\n) \n/ \n( \n    sum(increase(core_tracker_expect_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__range])) by (duty) \n) > 0",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Beacon Node Score",
   "type": "gauge",
   "description": "Average beacon node score for the whole time window. The score is a combination of:\n - **errors**: the ratio or errors returned by the beacon node \n - **latency**: how fast or slow the beacon node is responding\n\n\nThe performance of the Beacon node is critical to the performance of the validators and therefore rewards.  ",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(clamp(app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 1 OR app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 4 OR app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 5 OR app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 6, 1, 1) OR on() vector(0))\n*\n(\n    (\n0.5 * (1.0 - 10*(sum(increase(app_eth2_errors_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__range])) / (sum(increase(app_eth2_latency_seconds_count{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__range]))))) OR on() vector(0.5)\n    )\n    +\n    (\n        0.5 * (1.0 - clamp_max(histogram_quantile(0.99, sum(rate(app_eth2_latency_seconds_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__range])) by (le)),1))\n    )\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cluster Info",
   "type": "stat",
   "description": "Information about the charon cluster.\n\n- **Network**: The blockchain network \n- **Operators/Nodes**: The number of operators or nodes or peers in the charon DV cluster.\n- **Threshold**: The minimum number of participating nodes (also quorum).\n- **Validators**: The number of validators added to the cluster, each validator is staking 32 ETH. ",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "( 1 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"mainnet\"} )\nor \n( 2 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"goerli\"} )\nor\n( 3 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"sepolia\"} )\nor\n( 4 * app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", cluster_network=\"gnosis\"} )",
     "legendFormat": "Network"
    },
    {
     "expr": "cluster_operators{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Operators/Nodes"
    },
    {
     "expr": "cluster_threshold{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Threshold"
    },
    {
     "expr": "core_scheduler_validators_active{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Validators Active"
    },
    {
     "expr": "cluster_validators{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Validators Total"
    }
   ]
  },
  {
   "title": "Failing Health Checks",
   "type": "table",
   "description": "This panels shows any health checks that are failing. See <add link> for help troubleshooting.  \n\nNote the different severities:\n- **info**: Only informational, might not be an actual problem.\n- **warning**: Performance is degraded, operator intervention only required if this persists for a long time.\n- **critical**: Significant problem, validators probably not operation at all. Immediate operator intervention required.\n \n\n",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "sum(app_health_checks{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (name,severity) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer Connectivity and Missed Duties (🚧)",
   "type": "table",
   "description": "- **Peer**: The peer's name (inferred from their *charon-enr-private-key*)\n- **You**: ⭐️ is this local charon node\n- **Connected**: Whether you are currently connected to this peer.\n- **Direct**: Whether the connection is *direct* (👍) or *relay* (👎) \n- **Latency**: The time messages take to travel to/from the peer.\n- **Version**: The version of the peer's charon node\n- **Supported**: Whether the peers charon version is supported/compatible or not.\n- **Uptime**\" The duration since peer was restarted.\n- **🚧Attest**: Number of attestation duties missed in the time window.\n- **🚧Propose**: Number of block proposal duties missed in the time window.\n- **🚧Other**: Number of other duties missed in the time window.\n\n",
   "gridPos": { "h": 7, "w": 19, "x": 5, "y": 8 },
   "targets": [
    {
     "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__rate_interval])) by (le,peer))  * 1000"
    },
    {
     "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
    },
    {
     "expr": "(max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"direct\"}) by (peer)*10 + \nmax(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"relay\"}) by (peer))"
    },
    {
     "expr": "sum(app_peerinfo_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer,version) ",
     "legendFormat": "__auto"
    },
    {
     "expr": "time() - max(app_peerinfo_start_time_secs{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} > 0) by (peer)"
    },
    {
     "expr": "max(app_peerinfo_index{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"attester\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"attester\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=~\".*proposer\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=~\".*proposer\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty!~\"(proposer|attester)\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty!~\"(proposer|attester)\"}[$__range])) by (peer) \n) OR on() vector(0)",
     "legendFormat": "__auto"
    },
    {
     "expr": "max(app_peerinfo_version_support{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer) "
    }
   ]
  },
  {
   "title": "Overview Advanced",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Versions and Git Hashes",
     "type": "state-timeline",
     "gridPos": { "h": 5, "w": 7, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(app_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (version)",
       "legendFormat": "{{version}}"
      },
      {
       "expr": "max(app_git_commit{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (git_hash)",
       "legendFormat": "{{git_hash}}"
      },
      {
       "expr": "rate(app_start_time_secs{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) > 0",
       "legendFormat": "Restarts"
      }
     ]
    },
    {
     "title": "Historical Health Status",
     "type": "timeseries",
     "description": "Status returned from the `/readyz` health status endpoint. Unhealthy reasons include beacon node problems, charon p2p problems, or validator client problems.",
     "gridPos": { "h": 5, "w": 8, "x": 7, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Peer Connections (🟢=direct, 🟡=relay, 🔴=not connected)",
     "type": "state-timeline",
     "description": "Type of connections to each peer in the cluster during the time window:\n - 🟢 Green: Direct connection (this is the preferred)\n - 🟡 Yellow: Indirect relay connection (this is ok if only temporary)\n - 🔴 Red: No connection to peer (this is a problem)\n\nSee https://docs.obol.tech/docs/charon/networking#external-p2p-network",
     "gridPos": { "h": 5, "w": 9, "x": 15, "y": 24 },
     "targets": [
      {
       "expr": "(max(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer))\n+\n(1 * max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"relay\"}) by (peer))\n+ \n(100 * max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"direct\"}) by (peer))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Current Status",
     "type": "stat",
     "gridPos": { "h": 7, "w": 4, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "expr": "time() - max(app_start_time_secs{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
       "legendFormat": "Uptime"
      },
      {
       "expr": "core_scheduler_current_slot{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
       "legendFormat": "Slot"
      },
      {
       "expr": "core_scheduler_current_epoch{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
       "legendFormat": "Epoch"
      },
      {
       "expr": "core_scheduler_validators_active{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
       "legendFormat": "Validators Active"
      },
      {
       "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
       "legendFormat": "Charon Peers Connected"
      },
      {
       "expr": "sum(p2p_relay_connections{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) ",
       "legendFormat": "Relays Connected"
      },
      {
       "expr": "app_beacon_node_peers{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
       "legendFormat": "Beacon Node Peers"
      },
      {
       "expr": "p2p_reachability_status{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
       "legendFormat": "P2P Reachability"
      }
     ]
    },
    {
     "title": "Validators",
     "type": "table",
     "description": "Status and balance of each validator by public key with links to beaconcha.in.\n\nIf present, the \"❗️Peer Exits\" column indicate the number of peers that submitted partially signed exits for each validator.",
     "gridPos": { "h": 7, "w": 9, "x": 4, "y": 29 },
     "targets": [
      {
       "expr": "max(core_scheduler_validator_balance_gwei{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} / 1000000000) by (pubkey_full,pubkey, cluster_network)",
       "legendFormat": "{{pubkey}}"
      },
      {
       "expr": "max(core_scheduler_validator_status{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 1) by (pubkey, status)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(core_parsigdb_exit_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (pubkey) ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Warning(w) and Error(e) logs (per $interval)",
     "type": "timeseries",
     "description": "Warning (w) and error (e) logs grouped by topic. \n\nOccasional warns and errors are normal, but a significant increase indicate problems that require operators to investigate by looking at the actual logs entries.",
     "gridPos": { "h": 7, "w": 11, "x": 13, "y": 29 },
     "targets": [
      {
       "expr": "sum(increase(app_log_error_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (topic) > 0 ",
       "legendFormat": "e:{{topic}}"
      },
      {
       "expr": "sum(increase(app_log_warn_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (topic) > 0 ",
       "legendFormat": "w:{{topic}}"
      }
     ]
    },
    {
     "title": "Peer Connectivity and Missed Duties (🚧)",
     "type": "table",
     "description": "- **Peer**: The peer's name (inferred from their *charon-enr-private-key*)\n- **You**: ⭐️ is this local charon node\n- **Connected**: Whether you are currently connected to this peer.\n- **Direct**: Whether the connection is *direct* (👍) or *relay* (👎) \n- **Latency**: The time messages take to travel to/from the peer.\n- **Uptime**\" The duration since peer was restarted.\n- **ClockDiff**: Difference between local and peer's clock time. More than 2s is bad.\n- **🚧Attest**: Number of attestation duties missed in the time window.\n- **🚧Propose**: Number of block proposal duties missed in the time window.\n- **🚧Other**: Number of other duties missed in the time window.\n\n",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
      },
      {
       "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$__rate_interval])) by (le,peer))  * 1000"
      },
      {
       "expr": "sum(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
      },
      {
       "expr": "max(round(app_peerinfo_clock_offset_seconds{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"},0.1)*1000) by (peer) "
      },
      {
       "expr": "(max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"direct\"}) by (peer)*10 + \nmax(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"relay\"}) by (peer))"
      },
      {
       "expr": "sum(app_peerinfo_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer,version) ",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(app_peerinfo_git_commit{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer,git_hash) > 0",
       "legendFormat": "__auto"
      },
      {
       "expr": "time() - max(app_peerinfo_start_time_secs{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} > 0) by (peer)"
      },
      {
       "expr": "max(app_peerinfo_index{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)"
      },
      {
       "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"attester\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"attester\"}[$__range])) by (peer) \n) > 0 ",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"proposer\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=\"proposer\"}[$__range])) by (peer) \n) > 0 ",
       "legendFormat": "__auto"
      },
      {
       "expr": "(\n    sum(increase(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty!~\"(proposer|attester)\"}[$__range])) by (peer) \n/\n    sum(increase(core_tracker_participation_expected_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty!~\"(proposer|attester)\"}[$__range])) by (peer) \n) > 0 ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Duties", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "✅ Completed duties by type ",
   "type": "status-history",
   "description": "Completed duties by type over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum(increase(core_bcast_broadcast_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) > 0",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "✅ Successful Peer Participation: Duty=$duty",
   "type": "status-history",
   "description": "Successful duty participation per peer (filtered by selected duty) over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(rate(core_tracker_participation_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=~\"$peer\",duty=~\"$duty\"}[$interval])) by (peer) > 0 ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "❌ Failed duties by type (per $interval)",
   "type": "status-history",
   "description": "Failed duties by type over time. Use data link to show logs.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "sum(increase(core_tracker_failed_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) > 0",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "🚧 Missed Peer Participation: Duty=$duty",
   "type": "status-history",
   "description": "Missed duty participation per peer (filtered by selected duty) over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "sum(rate(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=~\"$peer\",duty=~\"$duty\"}[$interval])) by (peer) > 0 ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "❌ Failed duty percentage by type (per $interval)",
   "type": "timeseries",
   "description": "Failed duties percentage by type over time",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(\n    sum(increase(core_tracker_failed_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty)\n) \n/ \n(\n    sum(increase(core_tracker_failed_duties_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) \n    + \n    sum(increase(core_bcast_broadcast_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (duty) \n) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "🚧 Missed Peer Participation: Peer=$peer",
   "type": "status-history",
   "description": "Missed duty participation per duty (filtered by peer) over time.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 29 },
   "repeat": "peer",
   "targets": [
    {
     "expr": "sum(rate(core_tracker_participation_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=\"$peer\"}[$interval])) by (duty) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "🚨 Duty failure reason: $duty (per $interval)",
   "type": "timeseries",
   "description": "Number of failed duties by reason per time window. Note this is only available from v0.16.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "sum(increase(core_tracker_failed_duty_reasons_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}[$interval])) by (reason) > 0 ",
     "legendFormat": "{{.duty}}"
    }
   ]
  },
  {
   "title": "💥 Broadcasted duties never included on-chain (per $interval)",
   "type": "timeseries",
   "description": "Duties that was successfully broadcast to the Beacon Node, but that was never included on-chain. This could be due to broadcasting too late (too slow), but it could also just be to aspects of consensus layer out-of-our-control. See https://eth2book.info/bellatrix/part2/incentives/rewards/#remarks.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(increase(core_tracker_inclusion_missed_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\", duty=~\"$duty\"}[$interval])) by (duty)) > 0 ",
     "legendFormat": "{{duty}}"
    }
   ]
  },
  {
   "title": "Attestation Inclusion Delay (slots)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "slots" } },
   "targets": [
    {
     "expr": "sum(core_tracker_inclusion_delay{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
     "legendFormat": "Instant"
    },
    {
     "expr": "max(avg_over_time(core_tracker_inclusion_delay{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval]))",
     "legendFormat": "Avg"
    }
   ]
  },
  {
   "title": "Broadcast delay: $duty",
   "type": "timeseries",
   "description": "The delay after the start of the slot when the duty was successfully broadcasted. ",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.90, rate(core_bcast_broadcast_delay_seconds_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}[$interval]))) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus duration: $duty",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(histogram_quantile(0.90, increase(core_consensus_duration_seconds_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}[$interval]))) by (timer)",
     "legendFormat": "{{timer}}"
    }
   ]
  },
  {
   "title": "Consensus Rounds: $duty",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "max(core_consensus_decided_rounds{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}) by (timer)",
     "legendFormat": "{{timer}}"
    }
   ]
  },
  {
   "title": "🚨 Consensus Timeouts (per $interval)",
   "type": "timeseries",
   "description": "Number of consensus timeouts per time window.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "sum(increase(core_consensus_timeout_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",duty=~\"$duty\"}[$interval])) by (timer) > 0",
     "legendFormat": "{{.duty}}"
    }
   ]
  },
  {
   "title": "Process",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 77 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(go_memstats_alloc_bytes{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
       "legendFormat": "Allocated Memory"
      }
     ]
    },
    {
     "title": "CPU",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(irate(process_cpu_seconds_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval]))",
       "legendFormat": "CPU"
      }
     ]
    },
    {
     "title": "Go Routines and File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(go_goroutines{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
       "legendFormat": "Go Routines"
      },
      {
       "expr": "max(process_open_fds{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"})",
       "legendFormat": "File Descriptors"
      }
     ]
    },
    {
     "title": "Garbage Collection Duration (per $interval)",
     "type": "timeseries",
     "description": "Total time spent on garbage collection per interval",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max(increase(go_gc_duration_seconds_sum{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "Upstream Beacon Node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 78 } },
  {
   "type": "table",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 79 },
   "targets": [
    {
     "expr": "(\n  sum(app_beacon_node_version{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (version)\n)\n  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon Node API requests rate",
   "type": "timeseries",
   "description": "Upstream beacon node API request rate per second by endpoint",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max(rate(app_eth2_latency_seconds_count{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (endpoint) > 0 ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Beacon Node API request latency (90%)",
   "type": "timeseries",
   "description": "Upstream beacon node API request latency (90th percentile) by endpoint by timewindow",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(app_eth2_latency_seconds_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (le,endpoint)) ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "🚨 Beacon Node API error count (per $interval)",
   "type": "timeseries",
   "description": "Number of errors per endpoint per time window",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(increase(app_eth2_errors_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (endpoint) > 0 ",
     "legendFormat": "{{endpoint}}"
    }
   ]
  },
  {
   "title": "Beacon Node Score",
   "type": "timeseries",
   "description": "Beacon node score over time",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "clamp_min((clamp(app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 1 OR app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 4 OR app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 5 OR app_monitoring_readyz{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"} == 6, 1, 1) OR on() vector(0))\n*\n(\n    (\n0.5 * (1.0 - 10*(sum(increase(app_eth2_errors_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) / (sum(increase(app_eth2_latency_seconds_count{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval]))))) OR on() vector(0.5)\n    )\n    +\n    (\n        0.5 * (1.0 - clamp_max(histogram_quantile(0.99, sum(rate(app_eth2_latency_seconds_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (le)),1))\n    )\n), 0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Beacon node peer count",
   "type": "timeseries",
   "description": "Number of consensus layer P2P peers the beacon node is connected to",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 95 },
   "targets": [
    {
     "expr": "app_beacon_node_peers{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}",
     "legendFormat": "Peer count"
    }
   ]
  },
  {
   "title": "Downstream Validator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 102 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validator API requests rate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max(rate(core_validatorapi_request_latency_seconds_count{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (endpoint) > 0",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "Validator API request latency (90%)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 166 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(core_validatorapi_request_latency_seconds_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (le,endpoint)) ",
       "legendFormat": "{{endpoint}}"
      }
     ]
    },
    {
     "title": "🚨 Validator API error count (per $interval)",
     "type": "timeseries",
     "description": "Number of errors per endpoint per time window",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 173 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "max(increase(core_validatorapi_request_error_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (endpoint) > 0 ",
       "legendFormat": "{{endpoint}}"
      }
     ]
    }
   ]
  },
  { "title": "P2P Networking", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 103 } },
  {
   "title": "Peer Connections (🟢=direct, 🟡=relay, 🔴=not connected)",
   "type": "state-timeline",
   "description": "Type of connections to each peer in the cluster during the time window:\n - 🟢 Green: Direct connection (this is the preferred)\n - 🟡 Yellow: Indirect relay connection (this is ok if only temporary)\n - 🔴 Red: No connection to peer (this is a problem)\n\nSee https://docs.obol.tech/docs/charon/networking#external-p2p-network",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 104 },
   "targets": [
    {
     "expr": "(max(p2p_ping_success{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer))\n+\n(1 * max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"relay\"}) by (peer))\n+ \n(100 * max(p2p_peer_connection_types{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",type=\"direct\"}) by (peer))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer ping latency (90%)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=~\"$peer\"}[$interval])) by (le,peer))  ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Ping Errors",
   "type": "state-timeline",
   "description": "Time windows that contain ping errors per peer",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "expr": "sum(increase(p2p_ping_error_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=~\"$peer\"}[$interval])) by (peer) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Peer ping latency (90%) (heatmap)",
   "type": "heatmap",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 110 },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(p2p_ping_latency_secs_bucket{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=~\"$peer\"}[$interval])) by (le,peer))",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Ping Rate",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "max(rate(p2p_ping_latency_secs_count{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=~\"$peer\"}[$interval])) by (peer) ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "New P2P Connections (per $interval)",
   "type": "timeseries",
   "description": "Number of new libp2p connections per peer per time window",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 116 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(increase(p2p_peer_connection_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\",peer=~\"$peer\"}[$interval])) by (peer) > 0 ",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Clock Offset",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max(app_peerinfo_clock_offset_seconds{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=~\"$cluster_peer\"}) by (peer) ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Network Avg Rate Rx+Tx",
   "type": "timeseries",
   "description": "Avg Rate of P2P network bytes sent plus received per peer (bytes/second) ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 122 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(p2p_peer_network_receive_bytes_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (peer) + sum(rate(p2p_peer_network_sent_bytes_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (peer)",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Connected Relays",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "sum(p2p_relay_connections{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer) > 0 ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "P2P Network Bytes Rx+Tx (per $interval)",
   "type": "timeseries",
   "description": "Total P2P network bytes sent plus received per peer per time window (bytes per interval)",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 128 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(increase(p2p_peer_network_receive_bytes_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (peer) + sum(increase(p2p_peer_network_sent_bytes_total{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}[$interval])) by (peer)",
     "legendFormat": "{{peer}}"
    }
   ]
  },
  {
   "title": "Active libp2p streams",
   "type": "timeseries",
   "description": "The number of active libp2p streams by peer or relay. Note this can be further grouped by direction and protocol.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 134 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(p2p_peer_streams{cluster_name=\"$cluster_name\",cluster_hash=\"$cluster_hash\",cluster_peer=\"$cluster_peer\"}) by (peer)",
     "legendFormat": "{{peer}}"
    }
   ]
  }
 ]
}