apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1
  - name: Loki
    orgId: 1

# Custom IDs for Prometheus & Loki
datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    orgId: 1
    basicAuth: false
    isDefault: true
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    version: 1
    editable: true

  - name: Loki
    type: loki
    uid: loki
    orgId: 1
    basicAuth: false
    isDefault: false
    jsonData:
      graphiteVersion: "1.1"
      tlsAuth: false
      tlsAuthWithCACert: false
    version: 1
    editable: true
