
name: Publish images

on:
  push:
    branches: 
      - 'main'
      - 'feat-prometheus-client-container'

jobs:
  push_prometheus:
    name: Publish Prometheus image
    runs-on: ubuntu-latest
    
    permissions:
      packages: write
      contents: read
      id-token: write
      attestations: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/${{ github.repository }}/prometheus
          tags: |
            type=sha,format=short,value=${{ github.sha }}

      # Prometheus      
      - name: Build and push Prometheus
        id: push-prometheus
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: prometheus.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          
      - name: attest-prometheus
        uses: actions/attest-build-provenance@v1
        id: attest
        with:
          subject-name: ghcr.io/${{ github.repository }}/prometheus
          subject-digest: ${{ steps.push-prometheus.outputs.digest }}
          push-to-registry: true

      # Prometheus-Lido
      - name: Build and push Prometheus-lido
        id: push-prometheus-lido
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: prometheus-lido.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: attest-prometheus-lido  
        uses: actions/attest-build-provenance@v1
        id: attest-prometheus-lido
        with:
          subject-name: ghcr.io/${{ github.repository }}/prometheus-lido
          subject-digest: ${{ steps.push-prometheus-lido.outputs.digest }}
          push-to-registry: true

      # Grafana
      - name: Build and push Grafana
        id: push-grafana
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          file: grafana.Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: attest  
        uses: actions/attest-build-provenance@v1
        id: attest-grafana
        with:
          subject-name: ghcr.io/${{ github.repository }}/grafana
          subject-digest: ${{ steps.push-grafana.outputs.digest }}
          push-to-registry: true
          